### ISSUE TITLE
[2.5.14] publish and download feature when protected by a policy

### ISSUE THREAD

**Issue by SebastienDenvil** [ESGF/esgf-installer#274] opened 2017-10-03 13:25 UTC
We would like to know a publish and download data protected by policies on the 2.5.14 has been successful

We are having difficulties and would like to know if other have succeeded.

**Comment by SebastienDenvil** [comment] 2017-10-03 13:26
@alaniwi thank you for your proposition

**Comment by alaniwi** [comment] 2017-10-03 13:46
I am seeing a stack trace which includes the following:
```
javax.servlet.jsp.JspException: Problem accessing the absolute URL "file:???orp.provider.list???". java.io.FileNotFoundException:  (No such file or directory)
```

**Comment by SebastienDenvil** [comment] 2017-10-03 14:40
The same for us. And the orp seems broken
https://YOUR_NODE/esg-orp/home.htm

**Comment by alaniwi** [comment] 2017-10-03 15:51
I did `strace` on the process while making the client request (first request after restarting the server). There is no evidence that it is actually trying to open a file called `orp.provider.list` or anything similar.

The `/esg/config/esgf.properties` has `orp.provider.list=/esg/config/esgf_known_providers.xml`. The `esgf_known_providers.xml` file has correct world-readable file permissions, but `stat` shows that the last access time is before the last server restart.

**Comment by alaniwi** [comment] 2017-10-03 16:10
Not sure if this is relevant, but if I try an access with `wget` and a myproxy certificate, then I avoid this error, but I see:
```
esg.security.common.SAMLInvalidStatementException: SAML statement signature is invalid
        at esg.security.authn.service.impl.SAMLAuthenticationStatementFacadeImpl.validateAssertion(SAMLAuthenticationStatementFacadeImpl.java:200)
        at esg.security.authn.service.impl.SAMLAuthenticationStatementFacadeImpl.getAuthentication(SAMLAuthenticationStatementFacadeImpl.java:134)
        at esg.orp.app.AuthenticationFilter.attemptValidation(AuthenticationFilter.java:118)
        at esg.orp.app.AccessControlFilterTemplate.doFilter(AccessControlFilterTemplate.java:63)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at esg.orp.app.AccessControlFilterTemplate.doFilter(AccessControlFilterTemplate.java:67)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
        at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:478)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:789)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1437)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
```
wget and browser access are both successful with open access files.

**Comment by LucaCinquini** [comment] 2017-10-03 16:52
Hi, I am running 2.5.13 so I can't really say... I will be installing 2.5.14 on our data node later today or tomorrow and can let you know if things are working...

**Comment by LucaCinquini** [comment] 2017-10-04 09:10
I installed 2.5.14 on the JPL dev-node and was able to reproduce the problem. The fix is actually quite simple: 
o stop the node
o edit the file /usr/local/tomcat/webapps/esg-orp/WEB-INF/classes/esg-orp.properties
o add the following line (anywhere):
orp.provider.list=/esg/config/esgf_known_providers.xml
o restart the node

I need to investigate why this line is missing from the most recent version of the war file.

Notice also that even after fixing this problem I had a problem with the TDS, which I will detail in a new ticket.

**Comment by LucaCinquini** [comment] 2017-10-04 09:34
The reason for this problem is that the ORP code contained two copies of the file esg-orp.properties, one in conf/ and one in src/, and for some reason the build started picking up the version with the missing property. Now the two files are the same so it doesn't matter which version is picked up by the build. I issued a new ORP tag v2.9.7 which should be included in a patch release.

**Comment by alaniwi** [comment] 2017-10-04 10:02
If I do your hand-edit, it now works for me, in that it displays the pull down list, redirects to login on chosen provider.

However, when it returns to the data node, again I get same "SAML statement signature is invalid" problem inside `validateAssertion`. I am going to ask for a signed host certificate and hope this fixes that problem.

**Comment by glevava** [comment] 2017-10-04 18:51
Hi Luca, hi Alan, I hand-edit the esg-orp.properties too and fixed the issue with success !
But I don't encounter the SAML statement as Alan. Data download seems to work fine for me.

Thanks !

**Comment by alaniwi** [comment] 2017-10-05 09:05
I can confirm that the SAML error goes away when I install signed certificates.

**Comment by sashakames** [comment] 2017-10-06 20:34
Luca's correction to esg-orp has been integrated into v2.5.15-devel and pushed out to the mirrors for testing

**Closed** 2017-11-16 16:42 UTC
Labels: 2.5.14, 2.5.15
