### ISSUE TITLE
removal of /var/lib/pgsql by esg-purge breaks subsequent reinstall

### ISSUE THREAD

**Issue by alaniwi** [ESGF/esgf-installer#361] opened 2018-03-22 13:37 UTC
Removing `/var/lib/pgsql` during `esg-purge all` prevents postgres from starting (probably because it runs as a non-root user without write permission to recreate it), leading to the installer failing with `Cannot connect to the database`. The purge script should be changed to remove the relevant content from `/var/lib/pgsql` but not the directory itself.

**Comment by alaniwi** [comment] 2018-03-22 13:38
```
# grep pgsql /usr/local/bin/esg-purge.sh 
    rm -f /etc/pam_pgsql.conf
    rm -f /etc/pam_pgsql.conf.tmpl.bak
    rm -rf /usr/local/pgsql
    rm -rf /var/lib/pgsql   <--- the problem line
```

**Comment by alaniwi** [comment] 2018-03-23 07:46
It now seems likely that what is breaking the reinstall more is not the purge script, but the problem with the esgf.repo file in issue #360. This issue ought probably to be fixed, but the installation in fact tries to reinstall postgresql-server in any case, but is prevented from doing so because it first creates a corrupt esgf.repo file which breaks the yum install.

**Comment by pchengi** [comment] 2018-04-17 09:03
@alaniwi , since the issue is not really with esg-purge, I'll close this issue. I've also pulled in your suggested fix for issue 360, and I've not been able to reproduce the case which produces a corrupt esgf.repo file. If you can reproduce it, or see it happening again, please open a ticket with an appropriate title.

**Closed by pchengi** 2018-04-17 09:03 UTC
